menu:
    首页: /
    归档: /archives/
    GitHub: https://github.com/nullcc
    关于: /about/
    RSS: /atom.xml

favicon: /favicon.png
logo: /favicon.png
language: zh-CN

# Comment
# e.g disqus: seansun
disqus: seansun
duoshuo:

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2017
